# Created with podman-4.9.4-rhel
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-12-04T05:37:54Z"
  labels:
    app: jms
  name: jms
spec:
  containers:
  - name: redis
    image: docker.io/jumpserver/redis:7.2
    args:
    - redis-server
    ports:
    - containerPort: 80
      hostPort: 80
    volumeMounts:
    - name: data-host-0
      mountPath: /data
  - name: jms-core
    image: localhost/jumpserver/core:20241204
    args:
    - /data/jumpserver/jms
    - start
    volumeMounts:
    - name: data-host-0
      mountPath: /data
  - name: jms-koko
    image: localhost/jumpserver/koko:20241204
    args:
    - /data/koko/koko  
    volumeMounts:
    - name: data-host-0
      mountPath: /data
  - name: jms-web
    image: localhost/jumpserver/web:20241204
    args:
    - /usr/sbin/nginx
    volumeMounts:
    - name: data-host-0
      mountPath: /data
  volumes:
  - name: data-host-0
    hostPath:
      type: Directory
      path: /data
