[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
nodaemon=true
silent=true
minfds=65536

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:jms_web]
command=/data/jumpserver/jms start web
directory=/opt/jumpserver
autostart=true
user=nobody
redirect_stderr=true
stdout_logfile=/var/log/jms_web
environment=PATH="/opt/py3/bin:/usr/bin:/bin"

[program:jms_task]
command=/data/jumpserver/jms start task
directory=/opt/jumpserver
autostart=true
user=nobody
redirect_stderr=false
environment=PATH="/opt/py3/bin:/usr/bin:/bin"

[program:jms_koko]
command=/data/koko/koko
directory=/data/koko
autostart=true
user=nobody
redirect_stderr=false

[program:jms_lion]
command=/data/lion/lion
directory=/data/lion
autostart=true
user=nobody
redirect_stderr=false

[program:guacd]
command=/usr/sbin/guacd -f
autostart=true
user=guacd
redirect_stderr=false

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off'
autostart=true
user=root
redirect_stderr=false

[program:redis]
command=/usr/bin/redis-server
directory=/data/redis
autostart=true
user=redis
redirect_stderr=false