[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
nodaemon=true
silent=true
minfds=65536

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:jms_web]
command=/opt/jumpserver/jms start web
directory=/opt/jumpserver
autostart=true
user=nobody
redirect_stderr=true
stdout_logfile=/var/log/jms_web
environment=PATH="/opt/py3/bin:/usr/bin:/bin"

[program:jms_task]
command=/opt/jumpserver/jms start task
directory=/opt/jumpserver
autostart=true
user=nobody
redirect_stderr=true
stdout_logfile=/var/log/jms_web
environment=PATH="/opt/py3/bin:/usr/bin:/bin"

