daemon off;
user nginx;
worker_processes auto;
worker_cpu_affinity auto;
worker_rlimit_nofile 65536;

error_log  /data/logs/nginx.error.log warn;
pid        /tmp/nginx.pid;

events {
	use epoll;
	worker_connections 1024;
}

http {
	log_format  main  '$remote_addr - $host [$time_local] "$request" '
			'$status $body_bytes_sent "$http_referer" '
			'"$http_user_agent" "$http_x_forwarded_for"';

	access_log  /data/logs/nginx.access.log main;

	sendfile            on;
	server_tokens       off;
	tcp_nopush          on;
	tcp_nodelay         on;
	keepalive_timeout   65;
	types_hash_max_size 4096;

	gzip              on;
	gzip_static       on;
	gzip_buffers      256 4k;
	gzip_min_length   1k;
	gzip_disable      "msie6";
	gzip_http_version 1.1;
	gzip_vary         on;
	gzip_comp_level   4;
	gzip_proxied      any;
	gzip_types        text/plain text/css text/xml text/javascript image/svg+xml image/x-icon application/javascript application/x-javascript application/json application/xml;

	include             /etc/nginx/mime.types;
	default_type        application/octet-stream;

	upstream jms_core    { server 127.0.0.1:8080; }
	upstream jms_koko    { server 127.0.0.1:5000; }

	server {
		listen  80 default_server;
		server_name _;

		index index.html index.htm;
		client_max_body_size 5000m;

		location = /robots.txt {
			default_type text/html;
			add_header Content-Type "text/plain; charset=UTF-8";
			return 200 "User-agent: *\nDisallow: /\n";
		}

		location /web/health/ {
			access_log off;
			add_header Content-Type 'application/json';
			return 200 '{"status": "ok"}';
		}

		location /player/ {
			try_files $uri / /index.html;
			alias /data/webroot/player/;
		}

		# lina 
		location /ui/ {
			try_files $uri / /ui/index.html;
			alias /data/webroot/lina/;
		}
	
		# luna
		location /luna/ {
			try_files $uri / /index.html;
			alias /data/webroot/luna/;
		}

		location /download/ {
			alias /data/webroot/download/;
		}

		location / {
			rewrite ^/(.*)$ /ui/$1 last;
		}

		# koko
		location /koko/ {
			proxy_pass http://jms_koko;

			proxy_buffering off;
			proxy_request_buffering off;
			proxy_http_version 1.1;
			proxy_ignore_client_abort on;
			proxy_connect_timeout 600;
			proxy_send_timeout 600;
			proxy_read_timeout 600;
			send_timeout 6000;

			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header Host $host;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
		}

		# jumpserver core
		location ~ ^/(core|api|media)/ {
			proxy_pass http://jms_core;
			proxy_set_header Host $http_host;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		}

		# websocket
		location /ws/ {
			proxy_pass http://jms_core;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header Host $host;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_http_version 1.1;
			proxy_buffering off;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
		}


		# jumpserver media
		location /media/replay/ {
			add_header Content-Encoding gzip;
			root /data/jumpserver/data;
		}

		# jumpserver static files
		location /static/ {
			root /data/jumpserver/data;
		}

		location /private-media/ {
			internal;
			alias /data/jumpserver/data/media/;
		}

	}
}
